development:
  linkedin_client_id: <%= ENV["LINKEDIN_CLIENT_ID"] %>
  linkedin_client_secret: <%= ENV["LINKEDIN_CLIENT_SECRET"] %>
  linkedin_redirect_uri: "http://localhost:3000/auth/linkedin/callback"
